- hosts: vrouters
  gather_facts: false  # facts gathering is not supported at the moment
  tasks:
    - name: copy running startup
      netconf_rpc:
        rpc: copy-config
        xmlns: 'urn:ietf:params:xml:ns:netconf:base:1.0'
        content: |
          <target><startup/></target>
          <source><running/></source>
